all:
	gcc -o tcp-client tcp-client.c
	gcc -o tcp-server tcp-server.c
	gcc -o udp-client udp-client.c
	gcc -o udp-server udp-server.c
clean:
	rm -f tcp-client tcp-server udp-client udp-server
ser: cli.c ser.c
	gcc -o cli cli.c
	gcc -o ser ser.c
